package advancejava.quiz.trainer;

import java.util.Scanner;

public class QuestionService {
    public Question[] questions; /*
                                  * initially the values in the array will be null since we didnt allocate any
                                  * memory which stores non primitive datatype
                                  */

    public QuestionService(int size, Scanner sc) {

        questions = new Question[size]; // determining the size of array

        for (int i = 0; i < size; i++) {
            questions[i] = new Question(); /*
                                            * here we are creating an object for every non primitive datatype depending
                                            * on the number of questions.
                                            */

            System.out.print("Enter details for question number: " + (i + 1));

            // Setting Question ID
            System.out.print("\nQuestion ID: ");
            questions[i].setId(sc.nextInt());
            /*
             * sc.nextLine() present below, consumes the newline (\n) which is generated by
             * nextInt() after giving input and pressing enter
             */
            sc.nextLine();

            // Setting question
            System.out.print("\nEnter the question: ");
            questions[i].setQuestion(sc.nextLine());

            // Setting options
            System.out.print("\nEnter 4 Options: ");
            String[] opts = new String[4];
            for (int j = 0; j < opts.length; j++) {
                opts[j] = sc.nextLine();
            }
            questions[i].setOptions(opts);

            // Setting answers
            System.out.print("\nSet which option is the answer for the question: ");
            questions[i].setAnswer(sc.nextInt());
        }
    }

    public void displayQuestion(int index) {
        if (questions.length == 0 || questions[0] == null) {
            System.out.println("0 Questions available");
            return;
        }
        if (questions.length < index) {
            System.out.println("Give a valid question number");
        }
        System.out.printf("Question %d is: \t" + questions[index].getQuestion(), index+1);
    }

    public void displayAnswer(int index) {
        if (questions.length == 0 || questions[0] == null) {
            System.out.println("0 questions available");
        }
        if (questions.length < index) {
            System.out.println("Give proper question number");
        }
        System.out.printf("The answer for question number %d is: " + questions[index].getAnswer(), index+1);
    }

    public void displayOptions(int index) {
        if (questions.length == 0 || questions[0] == null) {
            System.out.println("0 questions available");
        }
        String[] options=questions[index].getOptions();
        for(int i=0;i<options.length;i++){
            System.out.println(options[i]);
        }
    }
}
